"""Phase 2 architecture

Revision ID: d2a36ececba8
Revises: ebefee30c87d
Create Date: 2026-07-03 22:02:24.688295

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd2a36ececba8'
down_revision = 'ebefee30c87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding_created', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('hazard_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('ai_latency', sa.Float(), nullable=True),
    sa.Column('translation_latency', sa.Float(), nullable=True),
    sa.Column('tts_latency', sa.Float(), nullable=True),
    sa.Column('sms_latency', sa.Float(), nullable=True),
    sa.Column('voice_latency', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazard_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_livelihood', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vulnerability_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preferred_channel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferred_alert_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_alert_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=50), nullable=True))

    with op.batch_alter_table('delivery_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('attempt_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('provider_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('failure_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_logs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('provider_response')
        batch_op.drop_column('attempt_number')
        batch_op.drop_column('pipeline_stage')

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_column('risk_level')
        batch_op.drop_column('last_alert_sent')
        batch_op.drop_column('preferred_alert_time')
        batch_op.drop_column('preferred_channel')
        batch_op.drop_column('district')
        batch_op.drop_column('vulnerability_score')
        batch_op.drop_column('population')
        batch_op.drop_column('primary_livelihood')

    op.drop_table('alert_jobs')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
